version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      REDIS_ARGS: "--requirepass jasonrocks --user jph on +@all -DEBUG ~* >jasonrocks"
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data

  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis

  redis-sentinel:
    image: "bitnami/redis-sentinel:latest"
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_USER=jph
      - REDIS_MASTER_PASSWORD=jasonrocks
      - REDIS_SENTINEL_PORT_NUMBER=26379
    ports:
      - '26379:26379'

  ioredis-app:
    image: ioredis-app
    container_name: ioredis-app
    environment:
      - SENTINEL_HOST=redis-sentinel
      - SENTINEL_PORT=26379
#       only need the REDIS_HOST and REDIS_PASSWORD if running simple_login.js instead of sentinel_login.js
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENTINEL_MASTER=mymaster
      - REDIS_PASSWORD=jasonrocks
      - REDIS_USERNAME=jph
      - WRITE_JSON=false
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - "./src/:/app"
      - "../data/:/data"
    depends_on:
      - redis
