version: '3.9'

services:
  ioredis-app:
    image: ioredis-app
    container_name: ioredis-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=jasonrocks
      - REDIS_USERNAME=jph
      - WRITE_JSON=false
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - "./scripts:/scripts"
