version: '3.9'

services:

  jedis-app:
    image: jedis-app
    container_name: jedis-app
    hostname: jedis-app
    environment:
      - REDIS_HOST=redis-10096.jphterra1.demo-rlec.redislabs.com
      - REDIS_PORT=10096
      - REDIS_PASSWORD=redis123
      - TRUSTSTORE_PASSWORD=jasonrocks
      - TRUSTSTORE_LOCATION=/usr/app/tls/client-truststore.jks
      - KEYSTORE_PASSWORD=jasonrocks
      - KEYSTORE_LOCATION=/usr/app/tls/client-keystore.p12
      - REDIS_USERNAME=jph
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
