version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    command: redis-server --tls-port 6379 --port 0 --tls-cert-file /scripts/tests/tls/redis.crt --tls-key-file /scripts/tests/tls/redis.key --tls-ca-cert-file /scripts/tests/tls/ca.crt --requirepass jasonrocks --aclfile /scripts/users.acl
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
      - ./scripts:/scripts

  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    hostname: insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis

  jedis-app:
    image: jedis-app
    container_name: jedis-app
    hostname: jedis-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=jasonrocks
      - TRUSTSTORE_PASSWORD=jasonrocks
      - KEYSTORE_PASSWORD=jasonrocks
      - REDIS_USERNAME=jph
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - "./src/:/app"
      - "./data/:/data"
    depends_on:
      - redis
