version: '3.9'

services:

  jedis-app:
    image: jedis-app
    container_name: jedis-app
    hostname: jedis-app
    environment:
      - SENTINEL_HOST=redis-sentinel
      - SENTINEL_PORT=26379
      - SENTINEL_MASTER=mymaster
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=jasonrocks
      - TRUSTSTORE_PASSWORD=jasonrocks
      - TRUSTSTORE_LOCATION=/usr/app/tls/client-truststore.jks
      - KEYSTORE_PASSWORD=jasonrocks
      - KEYSTORE_LOCATION=/usr/app/tls/client-keystore.p12
      - REDIS_USERNAME=jph
      - USE_SSL=true
      - WRITE_JSON=false
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - "./src/:/app"
      - "./data/:/data"
    networks:
      redissentinel_default: 
        ipv4_address: 192.168.96.3
networks:
   redissentinel_default:
      ipam:
        driver: default
        config:
          - subnet: 192.168.96.0/20
            gateway: 192.168.96.1
