version: '3.9'

services:
  python-app:
    image: python-app
    container_name: python-app
    environment:
      - SENTINEL_HOST=redis-sentinel
      - SENTINEL_PORT=26379
      - SENTINEL_MASTER=mymaster
      - REDIS_PASSWORD=jasonrocks
      - REDIS_USERNAME=jph
      - WRITE_JSON=false
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - "./scripts:/scripts"
